### ISSUE TITLE
please add the ability to customize the statusbar position of the extension

### ISSUE THREAD

**Issue by BobbyJonas** [igorskyflyer/vscode-project-version#4]
Currently, the statusbar position of the plugin is fixed, which doesn't seem to meet my requirements.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/42066237/180914089-94ae4d2d-98b2-4671-a4b0-e3bcb22fe24d.png">

Is it possible to allow users to customize the statusbar position of the extension,
as the following screenshot shows, 
by exposing these two properties like the extension **Select Line Status Bar** did?

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/42066237/180914788-ad185adb-92f3-4d75-b6b5-5ee815be2881.png">

**Comment by igorskyflyer** [comment]
Yes, it is possible, I already have that implemented in another of my extensions, I'll publish a new version sometime Thu - Fri. 😁🤟🏼

**Comment by igorskyflyer** [comment]
I've just pushed the extension to the Marketplace with the desired functionality, it should be available for download soon. 😁
Please consider giving a 5⭐ rating for the extension if you find it useful, it means a lot, thanks. 😊

**Comment by BobbyJonas** [comment]
Thanks a lot. 😄

like this extension and i have given a rate.

**Comment by igorskyflyer** [comment]
> Thanks a lot. 😄
> 
> like this extension and i have given a rate.

Thank you, I just saw your review, thanks for the kind words. 😄✌🏽

I'll keep improving the extension, I already have another enhancement in mind, will release it soon. 🤯😌
